# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.paginated_company_merge_list import PaginatedCompanyMergeList

class TestPaginatedCompanyMergeList(unittest.TestCase):
    """PaginatedCompanyMergeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedCompanyMergeList:
        """Test PaginatedCompanyMergeList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedCompanyMergeList`
        """
        model = PaginatedCompanyMergeList()
        if include_optional:
            return PaginatedCompanyMergeList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    financial_reports_generated_client.models.company_merge.CompanyMerge(
                        id = 56, 
                        shell_id = 56, 
                        canonical_id = 56, 
                        shell_name = '', 
                        canonical_name = '', 
                        pattern = '', 
                        confidence = 1.337, 
                        merged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reversed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PaginatedCompanyMergeList(
                count = 123,
                results = [
                    financial_reports_generated_client.models.company_merge.CompanyMerge(
                        id = 56, 
                        shell_id = 56, 
                        canonical_id = 56, 
                        shell_name = '', 
                        canonical_name = '', 
                        pattern = '', 
                        confidence = 1.337, 
                        merged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reversed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPaginatedCompanyMergeList(self):
        """Test PaginatedCompanyMergeList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
