# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.company_financial_statement import CompanyFinancialStatement

class TestCompanyFinancialStatement(unittest.TestCase):
    """CompanyFinancialStatement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyFinancialStatement:
        """Test CompanyFinancialStatement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyFinancialStatement`
        """
        model = CompanyFinancialStatement()
        if include_optional:
            return CompanyFinancialStatement(
                fiscal_year = 56,
                fiscal_period = '',
                period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                statement_type = '',
                statement_type_display = '',
                currency = financial_reports_generated_client.models.currency_compact.CurrencyCompact(
                    code = '', 
                    name = '', 
                    symbol = '', ),
                source_filing_id = 56,
                source_filing_release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                line_items = [
                    financial_reports_generated_client.models.financial_line_item_compact.FinancialLineItemCompact(
                        code = '', 
                        name = '', 
                        statement_type = '', 
                        depth = 56, 
                        parent_code = '', 
                        sort_order = 56, 
                        value = '-80728880015280217.09', 
                        raw_value = '-807288.015', 
                        scale = '', )
                    ]
            )
        else:
            return CompanyFinancialStatement(
                fiscal_year = 56,
                fiscal_period = '',
                period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                statement_type = '',
                statement_type_display = '',
                currency = financial_reports_generated_client.models.currency_compact.CurrencyCompact(
                    code = '', 
                    name = '', 
                    symbol = '', ),
                source_filing_id = 56,
                source_filing_release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                line_items = [
                    financial_reports_generated_client.models.financial_line_item_compact.FinancialLineItemCompact(
                        code = '', 
                        name = '', 
                        statement_type = '', 
                        depth = 56, 
                        parent_code = '', 
                        sort_order = 56, 
                        value = '-80728880015280217.09', 
                        raw_value = '-807288.015', 
                        scale = '', )
                    ],
        )
        """

    def testCompanyFinancialStatement(self):
        """Test CompanyFinancialStatement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
