# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.webhook_filing_payload import WebhookFilingPayload

class TestWebhookFilingPayload(unittest.TestCase):
    """WebhookFilingPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookFilingPayload:
        """Test WebhookFilingPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookFilingPayload`
        """
        model = WebhookFilingPayload()
        if include_optional:
            return WebhookFilingPayload(
                id = '',
                processing_status = '',
                filing_type_code = '',
                filing_type_name = '',
                language_code = '',
                language_name = '',
                title = '',
                dissemination_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                document_url = '',
                markdown_content = ''
            )
        else:
            return WebhookFilingPayload(
                id = '',
                processing_status = '',
                filing_type_code = '',
                filing_type_name = '',
                language_code = '',
                language_name = '',
                title = '',
                dissemination_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                document_url = '',
                markdown_content = '',
        )
        """

    def testWebhookFilingPayload(self):
        """Test WebhookFilingPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
