# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.webhooks_management_api import WebhooksManagementApi


class TestWebhooksManagementApi(unittest.IsolatedAsyncioTestCase):
    """WebhooksManagementApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WebhooksManagementApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_webhooks_create(self) -> None:
        """Test case for webhooks_create

        Create Webhook
        """
        pass

    async def test_webhooks_deliveries_replay_create(self) -> None:
        """Test case for webhooks_deliveries_replay_create

        Replay Delivery
        """
        pass

    async def test_webhooks_deliveries_retrieve(self) -> None:
        """Test case for webhooks_deliveries_retrieve

        List Delivery Logs
        """
        pass

    async def test_webhooks_delivery_detail_retrieve(self) -> None:
        """Test case for webhooks_delivery_detail_retrieve

        Retrieve Delivery Detail
        """
        pass

    async def test_webhooks_destroy(self) -> None:
        """Test case for webhooks_destroy

        Delete Webhook
        """
        pass

    async def test_webhooks_list(self) -> None:
        """Test case for webhooks_list

        List Webhooks
        """
        pass

    async def test_webhooks_partial_update(self) -> None:
        """Test case for webhooks_partial_update

        Partial Update Webhook
        """
        pass

    async def test_webhooks_regenerate_secret_create(self) -> None:
        """Test case for webhooks_regenerate_secret_create

        Regenerate Secret Key
        """
        pass

    async def test_webhooks_retrieve(self) -> None:
        """Test case for webhooks_retrieve

        Retrieve Webhook
        """
        pass

    async def test_webhooks_test_create(self) -> None:
        """Test case for webhooks_test_create

        Test Webhook
        """
        pass

    async def test_webhooks_update(self) -> None:
        """Test case for webhooks_update

        Update Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
