# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.bulk_watchlist_response import BulkWatchlistResponse

class TestBulkWatchlistResponse(unittest.TestCase):
    """BulkWatchlistResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkWatchlistResponse:
        """Test BulkWatchlistResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkWatchlistResponse`
        """
        model = BulkWatchlistResponse()
        if include_optional:
            return BulkWatchlistResponse(
                status = '',
                message = '',
                company_ids = [
                    56
                    ]
            )
        else:
            return BulkWatchlistResponse(
                status = '',
                message = '',
        )
        """

    def testBulkWatchlistResponse(self):
        """Test BulkWatchlistResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
