# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.companies_financials_retrieve200_response import CompaniesFinancialsRetrieve200Response

class TestCompaniesFinancialsRetrieve200Response(unittest.TestCase):
    """CompaniesFinancialsRetrieve200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesFinancialsRetrieve200Response:
        """Test CompaniesFinancialsRetrieve200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesFinancialsRetrieve200Response`
        """
        model = CompaniesFinancialsRetrieve200Response()
        if include_optional:
            return CompaniesFinancialsRetrieve200Response(
                company_id = 56,
                currency = financial_reports_generated_client.models.companies_financials_retrieve_200_response_currency.companies_financials_retrieve_200_response_currency(
                    code = '', 
                    name = '', 
                    symbol = '', ),
                sources_masked = True,
                filters = financial_reports_generated_client.models.companies_financials_retrieve_200_response_filters.companies_financials_retrieve_200_response_filters(
                    statement_type = '', 
                    fiscal_year = 56, 
                    fiscal_year_from = 56, 
                    fiscal_year_to = 56, 
                    fiscal_period = '', 
                    line_items = [
                        ''
                        ], 
                    as_of = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                period_count = 56,
                periods = [
                    financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner.companies_financials_retrieve_200_response_periods_inner(
                        fiscal_year = 56, 
                        fiscal_period = '', 
                        period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        statements = [
                            None
                            ], )
                    ]
            )
        else:
            return CompaniesFinancialsRetrieve200Response(
                company_id = 56,
                sources_masked = True,
                filters = financial_reports_generated_client.models.companies_financials_retrieve_200_response_filters.companies_financials_retrieve_200_response_filters(
                    statement_type = '', 
                    fiscal_year = 56, 
                    fiscal_year_from = 56, 
                    fiscal_year_to = 56, 
                    fiscal_period = '', 
                    line_items = [
                        ''
                        ], 
                    as_of = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                period_count = 56,
                periods = [
                    financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner.companies_financials_retrieve_200_response_periods_inner(
                        fiscal_year = 56, 
                        fiscal_period = '', 
                        period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        statements = [
                            None
                            ], )
                    ],
        )
        """

    def testCompaniesFinancialsRetrieve200Response(self):
        """Test CompaniesFinancialsRetrieve200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
