# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.isic_classifications_api import ISICClassificationsApi


class TestISICClassificationsApi(unittest.IsolatedAsyncioTestCase):
    """ISICClassificationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ISICClassificationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_isic_classes_list(self) -> None:
        """Test case for isic_classes_list

        List ISIC Classes
        """
        pass

    async def test_isic_classes_retrieve(self) -> None:
        """Test case for isic_classes_retrieve

        Retrieve ISIC Class
        """
        pass

    async def test_isic_divisions_list(self) -> None:
        """Test case for isic_divisions_list

        List ISIC Divisions
        """
        pass

    async def test_isic_divisions_retrieve(self) -> None:
        """Test case for isic_divisions_retrieve

        Retrieve ISIC Division
        """
        pass

    async def test_isic_groups_list(self) -> None:
        """Test case for isic_groups_list

        List ISIC Groups
        """
        pass

    async def test_isic_groups_retrieve(self) -> None:
        """Test case for isic_groups_retrieve

        Retrieve ISIC Group
        """
        pass

    async def test_isic_sections_list(self) -> None:
        """Test case for isic_sections_list

        List ISIC Sections
        """
        pass

    async def test_isic_sections_retrieve(self) -> None:
        """Test case for isic_sections_retrieve

        Retrieve ISIC Section
        """
        pass


if __name__ == '__main__':
    unittest.main()
