# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.companies_financials_retrieve200_response_periods_inner_statements_inner_sources_inner import CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner

class TestCompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner(unittest.TestCase):
    """CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner:
        """Test CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner`
        """
        model = CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner()
        if include_optional:
            return CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner(
                filing_id = 56,
                filing_type = '',
                release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_selected = True
            )
        else:
            return CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner(
        )
        """

    def testCompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner(self):
        """Test CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerSourcesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
