# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.companies_financials_retrieve200_response_periods_inner import CompaniesFinancialsRetrieve200ResponsePeriodsInner

class TestCompaniesFinancialsRetrieve200ResponsePeriodsInner(unittest.TestCase):
    """CompaniesFinancialsRetrieve200ResponsePeriodsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesFinancialsRetrieve200ResponsePeriodsInner:
        """Test CompaniesFinancialsRetrieve200ResponsePeriodsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesFinancialsRetrieve200ResponsePeriodsInner`
        """
        model = CompaniesFinancialsRetrieve200ResponsePeriodsInner()
        if include_optional:
            return CompaniesFinancialsRetrieve200ResponsePeriodsInner(
                fiscal_year = 56,
                fiscal_period = '',
                period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                statements = [
                    financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner_statements_inner.companies_financials_retrieve_200_response_periods_inner_statements_inner(
                        statement_type = 'IS', 
                        statement_type_display = '', 
                        currency = financial_reports_generated_client.models.companies_financials_retrieve_200_response_currency.companies_financials_retrieve_200_response_currency(
                            code = '', 
                            name = '', 
                            symbol = '', ), 
                        currency_mismatch = True, 
                        extraction = financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner_statements_inner_extraction.companies_financials_retrieve_200_response_periods_inner_statements_inner_extraction(
                            model = '', 
                            prompt_version = '', 
                            extracted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            notes = '', ), 
                        line_items = [
                            financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner_statements_inner_line_items_inner.companies_financials_retrieve_200_response_periods_inner_statements_inner_line_items_inner(
                                code = '', 
                                name = '', 
                                statement_type = 'IS', 
                                depth = 56, 
                                parent_code = '', 
                                sort_order = 56, 
                                value = '', 
                                raw_value = '', 
                                scale = 'units', 
                                currency = '', 
                                confidence = 1.337, 
                                source_page = 56, 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        is_comparative = True, 
                        source_filing = financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner_statements_inner_source_filing.companies_financials_retrieve_200_response_periods_inner_statements_inner_source_filing(
                            id = 56, 
                            filing_type = '', 
                            release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            document_url = '', 
                            viewer_url = '', ), 
                        sources = [
                            financial_reports_generated_client.models.companies_financials_retrieve_200_response_periods_inner_statements_inner_sources_inner.companies_financials_retrieve_200_response_periods_inner_statements_inner_sources_inner(
                                filing_id = 56, 
                                filing_type = '', 
                                release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                is_selected = True, )
                            ], )
                    ]
            )
        else:
            return CompaniesFinancialsRetrieve200ResponsePeriodsInner(
        )
        """

    def testCompaniesFinancialsRetrieve200ResponsePeriodsInner(self):
        """Test CompaniesFinancialsRetrieve200ResponsePeriodsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
