# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.filing import Filing

class TestFiling(unittest.TestCase):
    """Filing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Filing:
        """Test Filing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Filing`
        """
        model = Filing()
        if include_optional:
            return Filing(
                id = 56,
                company = financial_reports_generated_client.models.company_minimal.CompanyMinimal(
                    id = 56, 
                    name = '', 
                    tagline = '', 
                    isins = [
                        ''
                        ], 
                    lei = '', 
                    sub_industry_code = '', 
                    country_code = '', ),
                filing_type = financial_reports_generated_client.models.filing_type.FilingType(
                    id = 56, 
                    code = '', 
                    name = '', 
                    description = '', 
                    category = null, ),
                language = financial_reports_generated_client.models.language.Language(
                    id = 56, 
                    code = '', 
                    name = '', ),
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                title = '',
                added_to_platform = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                dissemination_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                release_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = financial_reports_generated_client.models.source.Source(
                    id = 56, 
                    name = '', 
                    url = '', 
                    description = '', ),
                document = '',
                proxy_url = '',
                viewer_url = '',
                file_extension = '',
                file_size = 0,
                markdown_url = '',
                filing_type_confidence = 1.337,
                filing_type_reasoning = '',
                fiscal_year = 56,
                fiscal_period = 'FY',
                period_ending_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return Filing(
                id = 56,
                company = financial_reports_generated_client.models.company_minimal.CompanyMinimal(
                    id = 56, 
                    name = '', 
                    tagline = '', 
                    isins = [
                        ''
                        ], 
                    lei = '', 
                    sub_industry_code = '', 
                    country_code = '', ),
                filing_type = financial_reports_generated_client.models.filing_type.FilingType(
                    id = 56, 
                    code = '', 
                    name = '', 
                    description = '', 
                    category = null, ),
                language = financial_reports_generated_client.models.language.Language(
                    id = 56, 
                    code = '', 
                    name = '', ),
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                added_to_platform = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = financial_reports_generated_client.models.source.Source(
                    id = 56, 
                    name = '', 
                    url = '', 
                    description = '', ),
                document = '',
                proxy_url = '',
                viewer_url = '',
                markdown_url = '',
                filing_type_confidence = 1.337,
                filing_type_reasoning = '',
                fiscal_year = 56,
                fiscal_period = 'FY',
                period_ending_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testFiling(self):
        """Test Filing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
