# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.IsolatedAsyncioTestCase):
    """CompaniesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CompaniesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_companies_api_company_financials_gsheet_export_create(self) -> None:
        """Test case for companies_api_company_financials_gsheet_export_create

        """
        pass

    async def test_companies_api_company_financials_gsheet_export_retrieve(self) -> None:
        """Test case for companies_api_company_financials_gsheet_export_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
