# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.security_listing import SecurityListing

class TestSecurityListing(unittest.TestCase):
    """SecurityListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityListing:
        """Test SecurityListing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityListing`
        """
        model = SecurityListing()
        if include_optional:
            return SecurityListing(
                id = 56,
                company = financial_reports_generated_client.models.company_minimal.CompanyMinimal(
                    id = 56, 
                    name = '', 
                    tagline = '', 
                    isins = [
                        ''
                        ], 
                    lei = '', 
                    sub_industry_code = '', 
                    country_code = '', ),
                mic = '',
                ticker = '',
                exch_code = '',
                exchange_name = '',
                security_type = '',
                market_sector = '',
                figi = '',
                composite_figi = '',
                share_class_figi = ''
            )
        else:
            return SecurityListing(
                id = 56,
                company = financial_reports_generated_client.models.company_minimal.CompanyMinimal(
                    id = 56, 
                    name = '', 
                    tagline = '', 
                    isins = [
                        ''
                        ], 
                    lei = '', 
                    sub_industry_code = '', 
                    country_code = '', ),
                mic = '',
                ticker = '',
                exch_code = '',
                exchange_name = '',
                security_type = '',
                market_sector = '',
                figi = '',
                composite_figi = '',
                share_class_figi = '',
        )
        """

    def testSecurityListing(self):
        """Test SecurityListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
