# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.watchlist_api import WatchlistApi


class TestWatchlistApi(unittest.IsolatedAsyncioTestCase):
    """WatchlistApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WatchlistApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_watchlist_companies_bulk_add_create(self) -> None:
        """Test case for watchlist_companies_bulk_add_create

        Bulk Add Companies to Watchlist
        """
        pass

    async def test_watchlist_companies_bulk_remove_create(self) -> None:
        """Test case for watchlist_companies_bulk_remove_create

        Bulk Remove Companies from Watchlist
        """
        pass

    async def test_watchlist_companies_create(self) -> None:
        """Test case for watchlist_companies_create

        Add Company to Watchlist
        """
        pass

    async def test_watchlist_companies_destroy(self) -> None:
        """Test case for watchlist_companies_destroy

        Remove Company from Watchlist
        """
        pass

    async def test_watchlist_retrieve(self) -> None:
        """Test case for watchlist_retrieve

        Get User's Watchlist
        """
        pass


if __name__ == '__main__':
    unittest.main()
