"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.3.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "financial-reports-generated-client"
VERSION = "1.4.59"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "python-dateutil >= 2.8.2",
    "aiohttp >= 3.14.1",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="FinancialFilings API",
    author="API Support",
    author_email="api@financialreports.eu",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "FinancialFilings API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Public-company filings across G20 markets and Europe. Authenticate every request with the &#x60;X-API-Key&#x60; header. Rate-limit headers on authenticated API responses: &#x60;X-RateLimit-Burst-Limit&#x60; (a rate expression such as &#x60;50/second&#x60;, not an integer), &#x60;X-RateLimit-Monthly-Limit&#x60; (an integer or the literal &#x60;Unlimited&#x60;), &#x60;X-RateLimit-Monthly-Remaining&#x60; (an integer, or &#x60;Unlimited&#x60; / &#x60;MCP (unlimited)&#x60;; omitted when not applicable), and &#x60;X-RateLimit-Monthly-Unit&#x60; (&#x60;requests&#x60; or &#x60;credits&#x60; — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.
    """,  # noqa: E501
    package_data={"financial_reports_generated_client": ["py.typed"]},
)
