# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerLineItemsInner(BaseModel):
    """
    CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerLineItemsInner
    """ # noqa: E501
    code: StrictStr
    name: StrictStr
    statement_type: StrictStr = Field(description="The KPI's home statement in the taxonomy, which can differ from the statement it was extracted onto. `SUP` appears here but is never a statement type.")
    depth: StrictInt
    parent_code: Optional[StrictStr]
    sort_order: StrictInt
    value: Optional[StrictStr] = Field(description="Value in absolute units, as an exact DECIMAL STRING - not a number. Parse with a decimal type; float loses precision at financial magnitudes. NULL when the figure was quarantined as unrecoverable.")
    raw_value: Optional[StrictStr] = Field(description="The figure as printed in the document, as an exact decimal string. NULL - together with `scale` - when `value` is null, or when `value` was rebuilt by a repair sweep (the `balanced_plug` and `debt_hierarchy` derivations), because for those the printed figure was superseded and no `value == raw_value * scale` relationship holds. Note this does NOT cover every derived value: a `partial_aggregate` total is tagged at extraction time, where `raw_value` IS the value's provenance, so it is served normally.")
    scale: Optional[StrictStr] = Field(description="Reporting scale of `raw_value`. Withheld with it.")
    currency: Optional[StrictStr] = Field(description="The value's own currency code, which may differ from the statement's reporting currency for per-share figures. NULL for ratios.")
    confidence: Optional[Union[StrictFloat, StrictInt]] = Field(description="RESERVED - currently null on every line item. Nothing in the extraction pipeline writes this field. Do not branch on it.")
    source_page: Optional[StrictInt] = Field(description="RESERVED - currently null on every line item. Provenance is filing-level (`sources`), not page-level.")
    updated_at: datetime = Field(description="When this value was last written. Equal to the extraction time for an untouched value; moves when a later correction pass rewrites the value in place (a re-extraction replaces the whole statement and sets a new one). Compare it with the value from your previous poll to detect a changed figure without diffing. It does not move when a whole statement is withdrawn or when a different filing starts supplying the period - watch `source_filing` for that.")
    __properties: ClassVar[List[str]] = ["code", "name", "statement_type", "depth", "parent_code", "sort_order", "value", "raw_value", "scale", "currency", "confidence", "source_page", "updated_at"]

    @field_validator('statement_type')
    def statement_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['IS', 'BS', 'CFS', 'SUP']):
            raise ValueError("must be one of enum values ('IS', 'BS', 'CFS', 'SUP')")
        return value

    @field_validator('scale')
    def scale_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['units', 'thousands', 'lakhs', 'millions', 'crores', 'billions']):
            raise ValueError("must be one of enum values ('units', 'thousands', 'lakhs', 'millions', 'crores', 'billions')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerLineItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if parent_code (nullable) is None
        # and model_fields_set contains the field
        if self.parent_code is None and "parent_code" in self.model_fields_set:
            _dict['parent_code'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if raw_value (nullable) is None
        # and model_fields_set contains the field
        if self.raw_value is None and "raw_value" in self.model_fields_set:
            _dict['raw_value'] = None

        # set to None if scale (nullable) is None
        # and model_fields_set contains the field
        if self.scale is None and "scale" in self.model_fields_set:
            _dict['scale'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if source_page (nullable) is None
        # and model_fields_set contains the field
        if self.source_page is None and "source_page" in self.model_fields_set:
            _dict['source_page'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInnerLineItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "statement_type": obj.get("statement_type"),
            "depth": obj.get("depth"),
            "parent_code": obj.get("parent_code"),
            "sort_order": obj.get("sort_order"),
            "value": obj.get("value"),
            "raw_value": obj.get("raw_value"),
            "scale": obj.get("scale"),
            "currency": obj.get("currency"),
            "confidence": obj.get("confidence"),
            "source_page": obj.get("source_page"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


