# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.2.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompanyListing(BaseModel):
    """
    Inline schema type for the curated `listings[]` array on CompanySerializer.  These 6 fields are what ``CompanySerializer.get_listings`` returns — a de-duplicated, equity-only subset of ``SecurityListing`` rows.  Using an explicit serializer here (rather than ``SecurityListingSerializer``) keeps the OpenAPI contract tight and avoids advertising the 11-field full model shape that includes ``company``, ``market_sector``, etc.
    """ # noqa: E501
    mic: Optional[StrictStr]
    ticker: StrictStr
    exchange_name: Optional[StrictStr]
    exch_code: Optional[StrictStr]
    security_type: Optional[StrictStr]
    figi: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["mic", "ticker", "exchange_name", "exch_code", "security_type", "figi"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mic (nullable) is None
        # and model_fields_set contains the field
        if self.mic is None and "mic" in self.model_fields_set:
            _dict['mic'] = None

        # set to None if exchange_name (nullable) is None
        # and model_fields_set contains the field
        if self.exchange_name is None and "exchange_name" in self.model_fields_set:
            _dict['exchange_name'] = None

        # set to None if exch_code (nullable) is None
        # and model_fields_set contains the field
        if self.exch_code is None and "exch_code" in self.model_fields_set:
            _dict['exch_code'] = None

        # set to None if security_type (nullable) is None
        # and model_fields_set contains the field
        if self.security_type is None and "security_type" in self.model_fields_set:
            _dict['security_type'] = None

        # set to None if figi (nullable) is None
        # and model_fields_set contains the field
        if self.figi is None and "figi" in self.model_fields_set:
            _dict['figi'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mic": obj.get("mic"),
            "ticker": obj.get("ticker"),
            "exchange_name": obj.get("exchange_name"),
            "exch_code": obj.get("exch_code"),
            "security_type": obj.get("security_type"),
            "figi": obj.get("figi")
        })
        return _obj


