# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.3.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CompanyResolveStatusEnum(str, Enum):
    """
    * `matched` - Resolved to exactly one company * `matched_via_alias` - Reserved; never returned in this version * `ambiguous` - Several plausible companies — see candidates * `not_covered` - No company found
    """

    """
    allowed enum values
    """
    MATCHED = 'matched'
    MATCHED_VIA_ALIAS = 'matched_via_alias'
    AMBIGUOUS = 'ambiguous'
    NOT_COVERED = 'not_covered'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompanyResolveStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


