# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from financial_reports_generated_client.models.companies_financials_retrieve200_response_periods_inner_statements_inner import CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompaniesFinancialsRetrieve200ResponsePeriodsInner(BaseModel):
    """
    CompaniesFinancialsRetrieve200ResponsePeriodsInner
    """ # noqa: E501
    fiscal_year: Optional[StrictInt] = None
    fiscal_period: Optional[StrictStr] = None
    period_start_date: Optional[date] = None
    period_end_date: Optional[date] = None
    statements: Optional[List[CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInner]] = None
    __properties: ClassVar[List[str]] = ["fiscal_year", "fiscal_period", "period_start_date", "period_end_date", "statements"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponsePeriodsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in statements (list)
        _items = []
        if self.statements:
            for _item_statements in self.statements:
                _items.append(_item_statements.to_dict() if _item_statements is not None else None)
            _dict['statements'] = _items
        # set to None if fiscal_year (nullable) is None
        # and model_fields_set contains the field
        if self.fiscal_year is None and "fiscal_year" in self.model_fields_set:
            _dict['fiscal_year'] = None

        # set to None if fiscal_period (nullable) is None
        # and model_fields_set contains the field
        if self.fiscal_period is None and "fiscal_period" in self.model_fields_set:
            _dict['fiscal_period'] = None

        # set to None if period_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.period_start_date is None and "period_start_date" in self.model_fields_set:
            _dict['period_start_date'] = None

        # set to None if period_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.period_end_date is None and "period_end_date" in self.model_fields_set:
            _dict['period_end_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponsePeriodsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fiscal_year": obj.get("fiscal_year"),
            "fiscal_period": obj.get("fiscal_period"),
            "period_start_date": obj.get("period_start_date"),
            "period_end_date": obj.get("period_end_date"),
            "statements": [CompaniesFinancialsRetrieve200ResponsePeriodsInnerStatementsInner.from_dict(_item) for _item in obj["statements"]] if obj.get("statements") is not None else None
        })
        return _obj


