# coding: utf-8

"""
    FinancialReports API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Honor the `X-RateLimit-Burst-Remaining` response header.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.1.5
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompaniesFinancialsRetrieve200ResponseFilters(BaseModel):
    """
    CompaniesFinancialsRetrieve200ResponseFilters
    """ # noqa: E501
    statement_type: Optional[StrictStr] = None
    fiscal_year: Optional[StrictInt] = None
    fiscal_year_from: Optional[StrictInt] = None
    fiscal_year_to: Optional[StrictInt] = None
    fiscal_period: Optional[StrictStr] = None
    line_items: Optional[List[StrictStr]] = None
    as_of: Optional[date] = None
    __properties: ClassVar[List[str]] = ["statement_type", "fiscal_year", "fiscal_year_from", "fiscal_year_to", "fiscal_period", "line_items", "as_of"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponseFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompaniesFinancialsRetrieve200ResponseFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "statement_type": obj.get("statement_type"),
            "fiscal_year": obj.get("fiscal_year"),
            "fiscal_year_from": obj.get("fiscal_year_from"),
            "fiscal_year_to": obj.get("fiscal_year_to"),
            "fiscal_period": obj.get("fiscal_period"),
            "line_items": obj.get("line_items"),
            "as_of": obj.get("as_of")
        })
        return _obj


