# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FilingRemovedPayload(BaseModel):
    """
    FilingRemovedPayload
    """ # noqa: E501
    event_type: StrictStr = Field(description="Always 'filing.removed'.")
    webhook_id: StrictStr = Field(description="The ID of the webhook configuration that triggered this event.")
    filing_id: StrictStr = Field(description="The ID of the filing you should discard.")
    reason: StrictStr = Field(description="'deleted': the filing no longer exists. 'hidden': it was withdrawn from the platform. 'company_hidden': its company was withdrawn. 'out_of_scope': it was re-typed or moved to a company outside this webhook's filing types, watchlist or plan.  * `deleted` - deleted * `hidden` - hidden * `company_hidden` - company_hidden * `out_of_scope` - out_of_scope")
    triggered_at: datetime = Field(description="The timestamp (ISO 8601) when the event was triggered.")
    __properties: ClassVar[List[str]] = ["event_type", "webhook_id", "filing_id", "reason", "triggered_at"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['deleted', 'hidden', 'company_hidden', 'out_of_scope']):
            raise ValueError("must be one of enum values ('deleted', 'hidden', 'company_hidden', 'out_of_scope')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilingRemovedPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "event_type",
            "webhook_id",
            "filing_id",
            "reason",
            "triggered_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilingRemovedPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_type": obj.get("event_type"),
            "webhook_id": obj.get("webhook_id"),
            "filing_id": obj.get("filing_id"),
            "reason": obj.get("reason"),
            "triggered_at": obj.get("triggered_at")
        })
        return _obj


