# coding: utf-8

"""
    FinancialFilings API

    Public-company filings across G20 markets and Europe. Authenticate every request with the `X-API-Key` header. Rate-limit headers on authenticated API responses: `X-RateLimit-Burst-Limit` (a rate expression such as `50/second`, not an integer), `X-RateLimit-Monthly-Limit` (an integer or the literal `Unlimited`), `X-RateLimit-Monthly-Remaining` (an integer, or `Unlimited` / `MCP (unlimited)`; omitted when not applicable), and `X-RateLimit-Monthly-Unit` (`requests` or `credits` — pay-as-you-go free-tier accounts are metered in credits, not request counts; omitted whenever Monthly-Remaining is). Parse defensively — these are strings, not numbers.  **Tiered access.** **L1** — metadata, company profiles, ISIC classifications, reference data, point-in-time audit trails. **L2** — Markdown / JSON content, full-text search. **L3** — standardized financial line items (income statement, balance sheet, cash-flow statement) per fiscal period, mapped to a single reusable taxonomy.

    The version of the OpenAPI document: 1.4.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from financial_reports_generated_client.models.reason_enum import ReasonEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MarkdownNotFound(BaseModel):
    """
    404 body of `GET /filings/{id}/markdown/` (#997, #3514).
    """ # noqa: E501
    detail: StrictStr = Field(description="A human-readable message describing the error.")
    processing_status: StrictStr = Field(description="The filing's conversion status, e.g. `PENDING`, `QUEUED`, `PROCESSING`, `FAILED`, `SKIPPED`.")
    reason: ReasonEnum = Field(description="`not_processed`: no converted content yet. `no_narrative_content`: the source carries no narrative text. `content_missing`: a processed record exists but its content is unavailable.  * `not_processed` - not_processed * `no_narrative_content` - no_narrative_content * `content_missing` - content_missing")
    retryable: StrictBool = Field(description="`true` only while a conversion is scheduled or running; the response then carries a `Retry-After` header. When `false`, stop polling and wait for the filing's `markdown_url` to become non-null.")
    __properties: ClassVar[List[str]] = ["detail", "processing_status", "reason", "retryable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarkdownNotFound from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarkdownNotFound from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "detail": obj.get("detail"),
            "processing_status": obj.get("processing_status"),
            "reason": obj.get("reason"),
            "retryable": obj.get("retryable")
        })
        return _obj


